databases:
  - name: ask-ai-postgres
    plan: starter
    databaseName: askai
    user: askai_user

services:
  - type: web
    name: django-backend
    runtime: python
    branch: madhav-dev
    plan: starter
    buildCommand: "pip install -r django_backend/requirements.txt && python django_backend/manage.py migrate && python django_backend/manage.py collectstatic --noinput"
    startCommand: "cd django_backend && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ask-ai-postgres
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FASTAPI_SERVICE_URL
        sync: false
      - key: DEMO_MODE
        value: "false"

  - type: web
    name: fastapi-service
    runtime: python
    branch: madhav-dev
    plan: starter
    buildCommand: "pip install -r fastapi_service/requirements.txt"
    startCommand: "cd fastapi_service && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: LLM_MODEL
        value: "qwen/qwen3.8-27b"
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: "ask-ai"
      - key: DJANGO_INTERNAL_URL
        sync: false
      - key: VECTOR_DB_URL
        fromDatabase:
          name: ask-ai-postgres
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
